version: '3'

services:
  passwordsafe:
    container_name: PasswordSafe
    build:
        context: .
        args:
            - PWS_SERVER=10.1.50.222 # Password Safe application server
    ports: 
        - "80:80"
        - "443:443"